# Config file for Air
[build]
# Command to build the app
cmd = "go build -o cmd/gamevault/main cmd/gamevault/*.go"
# Binary to watch
bin = "cmd/gamevault/main"
# Working directory
dir = "."
# Patterns to watch
include_ext = ["go"]
# Exclude files
exclude_dir = ["vendor"]
# Command to run after build
run_after_build = "chmod +x cmd/gamevault/main"

[log]
level = "debug"

