CREATE TABLE IF NOT EXISTS games (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    title TEXT NOT NULL,
    year INTEGER NOT NULL,
    genres TEXT[] NOT NULL,
    platforms TEXT[] NOT NULL,
    developer TEXT NOT NULL,
    publisher TEXT NOT NULL,
    rating FLOAT NOT NULL DEFAULT 0,
    rating_count INTEGER NOT NULL DEFAULT 0,
    price BIGINT NOT NULL DEFAULT 0,
    version INTEGER DEFAULT 0
);
