basePath: /v1
definitions:
  data.Game:
    properties:
      developer:
        type: string
      genres:
        items:
          type: string
        type: array
      id:
        type: integer
      platform:
        items:
          type: string
        type: array
      price:
        type: integer
      publisher:
        type: string
      rating:
        type: number
      rating_count:
        type: integer
      title:
        type: string
      year:
        type: integer
    type: object
  main.GameCreateRequest:
    properties:
      developer:
        type: string
      genres:
        items:
          type: string
        type: array
      platform:
        items:
          type: string
        type: array
      price:
        minimum: 0
        type: integer
      publisher:
        type: string
      title:
        maxLength: 100
        minLength: 3
        type: string
      year:
        minimum: 1900
        type: integer
    required:
    - developer
    - genres
    - platform
    - publisher
    - title
    - year
    type: object
  main.GameResponse:
    properties:
      games:
        $ref: '#/definitions/data.Game'
    type: object
host: localhost:8000
info:
  contact:
    name: Jeisa Raja
    url: https://github.com/jeisaRaja
  description: sample desc
  title: GameVault API
  version: "1"
paths:
  /games/:
    post:
      consumes:
      - application/json
      description: This endpoint allows the user to create a new game in the system
        by providing necessary game details.
      parameters:
      - description: Game details
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/main.GameCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Game created successfully
          schema:
            $ref: '#/definitions/data.Game'
      summary: Create a new game entry
      tags:
      - Game
  /games/{id}:
    get:
      description: This endpoint retrieves the details of a specific game by its ID.
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Game details fetched successfully
          schema:
            $ref: '#/definitions/main.GameResponse'
        "404":
          description: Game not found
          schema:
            type: object
      summary: Show details of a specific game
      tags:
      - Game
    put:
      consumes:
      - application/json
      description: This endpoint allows the user to edit or update a game in the system
        by providing necessary game details.
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: integer
      - description: Game details
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/main.GameCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Game Updated
          schema:
            $ref: '#/definitions/data.Game'
      summary: Update a game entry
      tags:
      - Game
swagger: "2.0"
